services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./api/models:/app/models
    environment:
      - PYTHONUNBUFFERED=1

  streamlit:
    build: ./streamlit-app
    ports:
      - "8501:8501"
    depends_on:
      - api
    environment:
      - PYTHONUNBUFFERED=1

